#include "menubarui.h"

void MenuBarUI::prepare()
{
    // Initialize: Parents
    _build = new QMenu(translate("menu_build"), this);
    _edit = new QMenu(translate("menu_edit"), this);
    _file = new QMenu(translate("menu_file"), this);
    _help = new QMenu(translate("menu_help"), this);
    _project = new QMenu(translate("menu_project"), this);
    _scripts = new QMenu(translate("menu_scripts"), this);
    _window = new QMenu(translate("menu_window"), this);
    _tools = new QMenu(translate("menu_tools"), this);
    // Initialize: Children
    _about = new QAction(translate("item_about"), _help);
    _adb = new QMenu(translate("item_adb"), _tools);
    _applications_manager = new QAction(translate("item_applications_manager"), _tools);
    _build_ = new QAction(translate("item_build"), _build);
    _build_all = new QAction(translate("item_build_all"), _build);
    _clean = new QAction(translate("item_clean"), _build);
    _clean_all = new QAction(translate("item_clean_all"), _build);
    _close_file = new QAction(translate("item_close_file"), _file);
    _close_project = new QAction(translate("item_close_project"), _file);
    _contribute = new QAction(translate("item_contribute"), _help);
    _copy = new QAction(translate("item_copy"), _edit);
    _cut = new QAction(translate("item_cut"), _edit);
    _device_manager = new QAction(translate("item_device_manager"), _tools);
    _donate = new QAction(translate("item_donate"), _help);
    _export = new QAction(translate("item_export"), _project);
    _feedback = new QMenu(translate("item_feedback"), _help);
    _file_manager = new QAction(translate("item_file_manager"), _tools);
    _find = new QAction(translate("item_find"), _edit);
    _full_screen = new QAction(translate("item_full_screen"), _window);
    _full_screen->setCheckable(true);
    _goto = new QAction(translate("item_goto"), _edit);
    _logcat = new QAction(translate("item_logcat"), _tools);
    _open = new QMenu(translate("item_open"), _file);
    _paste = new QAction(translate("item_paste"), _edit);
    _print = new QAction(translate("item_print"), _file);
    _properties = new QAction(translate("item_properties"), _project);
    _quit = new QAction(translate("item_quit"), _file);
    _recent_files = new QMenu(translate("item_recent_files"), _file);
    _recent_projects = new QMenu(translate("item_recent_projects"), _file);
    _redo = new QAction(translate("item_redo"), _edit);
    _replace = new QAction(translate("item_replace"), _edit);
    _restart = new QAction(translate("item_restart"), _file);
    _save = new QAction(translate("item_save"), _file);
    _save_all = new QAction(translate("item_save_all"), _file);
    _shell = new QAction(translate("item_shell"), _tools);
    _sidebar = new QAction(translate("item_sidebar"), _window);
    _sidebar->setCheckable(true);
    _sign = new QAction(translate("item_sign"), _build);
    _split = new QAction(translate("item_split"), _window);
    _undo = new QAction(translate("item_undo"), _window);
    _views = new QMenu(translate("item_views"), _window);
    _windowed = new QAction(translate("item_windowed"), _window);
    _windowed->setCheckable(true);
    _zipalign = new QAction(translate("item_zipalign"), _build);
    // Initialize: Sub-Children
    _adb_kill = new QAction(translate("item_adb_kill"), _adb);
    _adb_reset = new QAction(translate("item_adb_reset"), _adb);
    _adb_start = new QAction(translate("item_adb_start"), _adb);
    _feedback_issues = new QAction(translate("item_feedback_issues"), _feedback);
    _feedback_thanks = new QAction(translate("item_feedback_thanks"), _feedback);
    _open_apk = new QAction(translate("item_open_apk"), _open);
    _open_file = new QAction(translate("item_open_file"), _open);
    _open_project = new QAction(translate("item_open_project"), _open);
    _views_files = new QAction(translate("item_views_files"), _views);
    _views_files->setCheckable(true);
    _views_logs = new QAction(translate("item_views_logs"), _views);
    _views_logs->setCheckable(true);
    _views_outline = new QAction(translate("item_views_outline"), _views);
    _views_outline->setCheckable(true);
    _views_projects = new QAction(translate("item_views_projects"), _views);
    _views_projects->setCheckable(true);
    _views_tasks = new QAction(translate("item_views_tasks"), _views);
    _views_tasks->setCheckable(true);
    // Add: Sub-Children
    QList<QAction *> adb;
    adb << _adb_kill << _adb_reset << _adb_start;
    _adb->addActions(adb);
    _feedback->addAction(_feedback_thanks);
    _feedback->addSeparator();
    _feedback->addAction(_feedback_issues);
    _open->addAction(_open_apk);
    _open->addAction(_open_project);
    _open->addSeparator();
    _open->addAction(_open_file);
    QList<QAction *> views;
    views << _views_files << _views_logs << _views_outline << _views_projects << _views_tasks;
    _views->addActions(views);
    // Add Children
    _build->addAction(_clean);
    _build->addAction(_clean_all);
    _build->addSeparator();
    _build->addAction(_build_);
    _build->addAction(_build_all);
    _build->addSeparator();
    _build->addAction(_sign);
    _build->addAction(_zipalign);
    _edit->addAction(_undo);
    _edit->addAction(_redo);
    _edit->addSeparator();
    _edit->addAction(_cut);
    _edit->addAction(_copy);
    _edit->addAction(_paste);
    _edit->addSeparator();
    _edit->addAction(_find);
    _edit->addAction(_replace);
    _edit->addAction(_goto);
    _file->addAction(_open->menuAction());
    _file->addSeparator();
    _file->addAction(_close_file);
    _file->addAction(_close_project);
    _file->addSeparator();
    _file->addAction(_save);
    _file->addAction(_save_all);
    _file->addSeparator();
    _file->addAction(_print);
    _file->addSeparator();
    _file->addAction(_restart);
    _file->addSeparator();
    _file->addAction(_recent_projects->menuAction());
    _file->addAction(_recent_files->menuAction());
    _file->addSeparator();
    _file->addAction(_quit);
    _help->addAction(_feedback->menuAction());
    _help->addSeparator();
    _help->addAction(_contribute);
    _help->addAction(_donate);
    _help->addSeparator();
    _help->addAction(_about);
    _project->addAction(_export);
    _project->addSeparator();
    _project->addAction(_properties);
    _tools->addAction(_adb->menuAction());
    _tools->addSeparator();
    _tools->addAction(_device_manager);
    _tools->addSeparator();
    _tools->addAction(_shell);
    _tools->addAction(_logcat);
    _tools->addSeparator();
    _tools->addAction(_file_manager);
    _tools->addAction(_applications_manager);
    _window->addAction(_windowed);
    _window->addAction(_full_screen);
    _window->addSeparator();
    _window->addAction(_sidebar);
    _window->addAction(_views->menuAction());
    _window->addSeparator();
    _window->addAction(_split);
    // Add: Parents
    addAction(_file->menuAction());
    addAction(_edit->menuAction());
    addAction(_build->menuAction());
    addAction(_project->menuAction());
    addAction(_tools->menuAction());
    addAction(_scripts->menuAction());
    addAction(_window->menuAction());
    addAction(_help->menuAction());
}
